### ISSUE TITLE
Missing snippets <fstfulapp>、 <fstless> and so on

### ISSUE THREAD

**Issue by DiscoverForever** [Alexisvt/flutter-snippets#4]
<img width="1223" alt="屏幕快照 2019-07-22 上午11 46 37" src="https://user-images.githubusercontent.com/16662687/61605051-6a3cd200-ac76-11e9-8f1a-2abbc1257dca.png">

vscode versio: v1.36.1

**Comment by Alexisvt** [comment]
Hi, I'm sorry for the late response, I've been busy at work these days, yes! Those snippets were remove in version 2.0, the reason was the official Flutter plugin already have snippets for those cases, what I did instead was actually complemented those with a new one that actually add the material package import, the name is `fimpmat` since the Flutter one doesn't import the package for you, it just adds the bare bond for the state/less widget. If you read the README file you can see the reason too, thanks for the head up.

**Comment by Alexisvt** [comment]
If you want to see which snippets are available in the official plugin, please follow the next link: https://github.com/Dart-Code/Dart-Code/blob/master/snippets/flutter.json

**Comment by DiscoverForever** [comment]
I got it, Thank you for your answer in your busy schedule.

**Comment by MuhammadimYusoff** [comment]
Then remove that snippets from your documentation!
I have been stuck there for about 1 hour configuring my snippet settings.

What a waste of time.

**Comment by Prathamesh-Shanbhag** [comment]
I am unable to find the alternatives already built in the flutter plugin,Can you tell me what it is?
Since using stful and stless are just giving the widgets and not the full  starter app snippet including scaffold etc?
