### ISSUE TITLE
Some snippets missing in menu

### ISSUE THREAD

**Issue by felixcollins** [Alexisvt/flutter-snippets#6]
I just installed 2.0.0 and when I type "fs" only some of the snippets are shown.

See the following:
![image](https://user-images.githubusercontent.com/1680258/82958152-e0356680-a008-11ea-9c82-5d973c13434f.png)

**Comment by Alexisvt** [comment]
Hi, sorry for the late reply, Could you please tell me which one is the one that you are looking for? On the README file you will find the complete list of commands, also I want to mention that the GIF image is outdated, and some of the command there are not valid anymore, if you want to know why I removed some of those please read the changelog section, also I’m planning to update that image to avoid future confusions, thanks for been interesting on this extension.

**Comment by felixcollins** [comment]
fstless for example is missing in the image above.

**Comment by Alexisvt** [comment]
Hi again, yes those were deleted because the dart extension already have those in it, I'm pointed that in this issue https://github.com/Alexisvt/flutter-snippets/issues/4, again all of these confusions are happening because I didn't update the GIF image, but I will do it this weekend and at the same time I will release a new version with more cool snippets!
